### ISSUE TITLE
Missing .aar

### ISSUE THREAD

**Issue by yahuuu** [lackhole/CuteModel#1]
I'm referencing your code to get my android DSP to do the calculations.
I extracted the following code and added it to the project:

nnapiOptions = tflite::StatefulNnApiDelegate::Options(); // nnapi
nnApiDelegate_ = new tflite::StatefulNnApiDelegate(nnapiOptions);
TfLiteInterpreterOptionsAddDelegate(options_, nnApiDelegate_);

But I can't find the right nnapi_delegate.h and tflite***nnapi.so, where can I download .aar that supports nnapi?

**Comment by lackhole** [comment]
@yahuuu You have to download the header file and library from the official tensorflow releases: https://www.tensorflow.org/lite/guide/build_arm64

**Comment by yahuuu** [comment]
I have solved the[ problem](https://github.com/tensorflow/tensorflow/issues/49947), thank you for your reply.

**Comment by lackhole** [comment]
@yahuuu Glad that I could help!
